#como preparar um miojo
print("pegue uma panela")
print("enche com metade da d'gua")
print("coloque no a panela no fogão")
print("acenda o fogão")
print("espere a panela borbulhar")
print("pegue o miojo")
print("abra o miojo")
print("tire o pozinho de dentro da embalagem do miojo")
print("jogue o miojo na panela já com a aguá fervendo")
print("espere o miojo cozinhar por 5 minutos")
print("pegue a panela e escorre um pouco d aagua do miojo")
print("pegue o pozinho do miojo")
print("jogue o pozinho no macarrão")
print("misture o miojo com o pozinho")
print("coloque o miojo no prato")
print("pegue um garfo")
print("coloque no prato")
print("come o miojo")
print("bom apetite")